AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - my.sample.service::springboot-sample
Resources:
  SpringbootSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.dranke.training.aws.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://dranke-learning-aws/2c08edd0174a654a3c34e6d7cc0afc2c
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  SpringbootSampleApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: SpringbootSampleApi
